sugarcube-2:
  macros:

    # live-update.js
    live:
      name: live
    l:
      name: l
    lh:
      name: lh
    liveblock:
      name: liveblock
      container: true
    lb:
      name: lb
      container: true
    update:
      name: update
    upd:
      name: upd

    # click-to-proceed.js
    ctp:
      name: ctp
      container: true
      children:
        - ctpNext
        - ctpHead
        - ctpTail
    ctpNext:
      name: ctpNext
      parents:
        - ctp
    ctpHead:
      name: ctpHead
      parents:
        - ctp
    ctpTail:
      name: ctpTail
      parents:
        - ctp
    ctpAdvance:
      name: ctpAdvance
    ctpBack:
      name: ctpBack